### PR TITLE
next13 - app folder

### PR DESCRIPTION
**Pull request by Rados51**
The only issues is that any `client` API calls are handled via `/v3/` and not via `/api/eventuras/v3/` with `OpenAPI.BASE`.
It should be possible to solve with middleware.

### CODE REVIEW

**Comment by losolio** [comment]
I want as little dependencies as possible, and was wondering if we could do our own slugify function... Something like: 

```js
// inspired by https://stackoverflow.com/a/17694737/4413516

function slugify(str) {
  str = str.toLowerCase();

  // replace spaces with hyphens
  var conversions = new Object();
  conversions["e"] = "æ|ä";
  conversions["o"] = "ø|ö";
  conversions["a"] = "å";

  for (var i in conversions) {
    var re = new RegExp(conversions[i], "g");
    str = str.replace(re, i);
  }

  return str
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "") // replace accented characters
    .replace(/[^a-z0-9 -]/g, "") // replace everything not a-z or number
    .replace(/\s+/g, "-"); //replace spaces with hyphens
}

// test
console.log(slugify("àâæøå-asdf#$%&/#&🥳 .....asdf"));

```

**Comment by losolio** [comment]
Thanks for this! It will be great if we land it.. Suggested plan:

I think we need to merge this down to main as soon as possible, as I would like to go live with the non-admin part of the frontend as soon as possible. So we will prioritize getting landing page, details page, authentication and event registration flow working.  

To get this landed we can comment/ toggle off code in the admin part, as long as it builds and run without security flaws.

**Comment by losolio** [comment]
If we run everything that is authenticated in server components, we are not in need of doing the accesstoken decorator in `app/api/eventuras/[...path]/route.ts`?

**Comment by Rados51** [comment]
> If we run everything that is authenticated in server components, we are not in need of doing the accesstoken decorator in `app/api/eventuras/[...path]/route.ts`?

I will need to first check the whole auth process

**Pull request merged**
